const rules = {
    'automatic-effect-dependencies': 2,
    'capitalized-calls': 2,
    'component-hook-factories': 2,
    'config': 2,
    'error-boundaries': 2,
    'exhaustive-deps': 2,
    'fbt': 2,
    'fire': 2,
    'gating': 2,
    'globals': 2,
    'hooks': 2,
    'immutability': 2,
    'incompatible-library': 2,
    'invariant': 2,
    'memoized-effect-dependencies': 2,
    'no-deriving-state-in-effects': 2,
    'preserve-manual-memoization': 2,
    'purity': 2,
    'refs': 2,
    'rule-suppression': 2,
    'rules-of-hooks': 2,
    'set-state-in-effect': 2,
    'set-state-in-render': 2,
    'static-components': 2,
    'syntax': 2,
    'todo': 2,
    'unsupported-syntax': 2,
    'use-memo': 2,
    'void-use-memo': 2,
};

export default Object.fromEntries(Object.entries(rules).map(e => [`hooks/${e[0]}`, e[1]]));
