const prettier = {
    arrowParens: 'avoid',
    bracketSameLine: false,
    bracketSpacing: true,
    checkIgnorePragma: true,
    embeddedLanguageFormatting: 'auto',
    endOfLine: 'lf',
    experimentalOperatorPosition: 'end',
    experimentalTernaries: false,
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    jsxSingleQuote: false,
    objectWrap: 'preserve',
    printWidth: 100,
    proseWrap: 'preserve',
    quoteProps: 'as-needed',
    requirePragma: false,
    semi: true,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: true,
};

export default prettier;
